Remove token from window.localStorage​ (fix XSS leak)
EstrellaXD/Auto_Bangumi pull request #579
Opened 2023-10-15 10:08 UTC by maikirakiwi

window.localStorage 很容易就能被浏览器的扩展程序读取，而JWT实现并不依赖于位于 localStorage 里的 auth 存储。Cookie 即可。

所以这么存 token 的方式属于严重白给。

在修改后的 auth 下只需要存登录态即可。

2023-10-15 10:13 UTC, maikirakiwi commented on webui/src/hooks/useAuth.ts
> +        auth.value = ``;
这里如果
- 设置为空：更改用户名/密码后将退回登录界面
- 设置为1（目前AB行为，虽然我觉得是bug）：保留在登录后的状态

2023-10-15 10:36 UTC, Rewrite0 requested changes
看样子是之前ek佬改登录方式的时候把这忘了，这个部分可以把原 `isLogin` 的 `computed` 移除， 将 `auth` 重命名为 `isLogin` 用于存放登录状态， 值用 `boolean` 就行， 这个 `hook` 在其他地方也有调用， 麻烦一并修改了

2023-10-15 10:36 UTC, Rewrite0 commented on webui/src/hooks/useAuth.ts
> +        auth.value = ``;
这里是之前更新账户信息后存储新token的逻辑，现在cookie登录可以不需要这段了

2023-10-15 13:23 UTC, Rewrite0 requested changes

2023-10-15 13:23 UTC, Rewrite0 commented on webui/src/App.vue
> +if (isLoggedin.value === true) {
不需要再 `=== true` 了

2023-10-15 13:23 UTC, Rewrite0 commented on webui/src/hooks/useAppInfo.ts
> +  const { isLoggedin } = useAuth();
把 `i` 大写

2023-10-15 13:23 UTC, Rewrite0 commented on webui/src/hooks/useAppInfo.ts
> +    if (isLoggedin.value !== false) {
不需要再 `!== false`

2023-10-15 13:23 UTC, Rewrite0 commented on webui/src/hooks/useAuth.ts
> +        isLoggedin.value = false;
可以不需要这个了， 免得重新登录

2023-10-15 13:23 UTC, Rewrite0 commented on webui/src/store/log.ts
> +    if (isLoggedin.value !== false) {
同上

2023-10-16 08:10 UTC, Rewrite0 approved these changes
approve

2023-10-16 08:10 UTC, merged